remote_theme: chrisrhymes/bulma-clean-theme

title: [The title of your site]
description: [A short description of your site's purpose]

fixed_navbar: top

- name: Contents
  link: /contents/
- name: Blog
  link: /blog/
