remote_theme: chrisrhymes/bulma-clean-theme

title: [The title of your site]
description: [A short description of your site's purpose]

fixed_navbar: top

- name: Page Name
  link: /page-1/
- name: Blog
  link: /blog/
